export interface IGenericMaster {
	readonly Factory: string,
	readonly Part: string,
	readonly Code: string,
	readonly PartName: string,
	readonly CodeName: string,
	readonly StringBuffer1: string,
	readonly StringBuffer2: string,
	readonly StringBuffer3: string,
	readonly StringBuffer4: string,
	readonly StringBuffer5: string,
	readonly NumericBuffer1: number,
	readonly NumericBuffer2: number,
	readonly NumericBuffer3: number,
	readonly NumericBuffer4: number,
	readonly NumericBuffer5: number,
}
